### ISSUE TITLE
500 When iso time has DST +0000

### ISSUE THREAD

**Issue by hamedaakhlaghi** [Carrene/restfulpy#148] opened 2018-01-20 13:48 UTC
Request:
https://nightly-ehr.carrene.com/apiv1/appointments?patientNumber=7204&providerCode=Albert&locationCode=Atlanta&reasonCode=ADD%20%26%20AHD&overrideReservation=false&duration=15&date=2017-02-07T19%3A30%3A00%2B0000

**Comment by memlucky71** [comment] 2018-03-18 14:36
mentioned date = `2017-02-07T19:30:00+0000`

**Comment by memlucky71** [comment] 2018-03-26 06:14
@pylover Based on [ISO 8061](https://en.wikipedia.org/wiki/ISO_8601), all of the following formats are valid: 

## Time Zones:
- Nothing, will use the default timezone given (which in turn defaults to UTC).
- Z (UTC)
- +/-hh:mm
- +/-hhmm
- +/-hh

## Times
- hh:mm:ss.nn
- hhmmss.nn
- hh:mm (defaults to 0 for seconds)
- hhmm (defaults to 0 for seconds)
- hh (defaults to 0 for minutes and seconds)

## Dates
- YYYY-MM-DD
- YYYYMMDD
- YYYY-MM (defaults to 1 for the day)
- YYYY (defaults to 1 for month and day)

Should we handle all these formats?

**Comment by pylover** [comment] 2018-03-26 06:34
Ok, So please write some tests for those variants.

**Comment by memlucky71** [comment] 2018-04-05 14:32
@pylover, POSIX timestamp is not supported by ISO 8061. By supporint YYYYMMDD or YYYY format for dates, we can't support POSIX timestamp anymore. what do you think?

**Comment by pylover** [comment] 2018-06-29 16:21
Cannot reproduce now, Maybe automatically fixed in my recent commits about date and time zone.

Anyway, I wrote some tests for this and currently, it is passing.

**Closed** 2018-06-29 16:22 UTC
Labels: bug
